# Generated by Django 5.1.7 on 2025-04-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_buy_and_sell', '0006_alter_banner_updated_at_alter_orderitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bike_buy_and_sell.chatmessage'),
        ),
    ]
